// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(OrionDbContext))]
    [Migration("20260926110609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.EDSystemName", b =>
                {
                    b.Property<long>("Id64")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id64"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id64");

                    b.ToTable("EDSystemName");
                });

            modelBuilder.Entity("Data.Models.FSDJump", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Conflicts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Faction")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FactionState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("FuelLevel")
                        .HasColumnType("float");

                    b.Property<double?>("FuelUsed")
                        .HasColumnType("float");

                    b.Property<double?>("JumpDist")
                        .HasColumnType("float");

                    b.Property<bool?>("NeedsPermit")
                        .HasColumnType("bit");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.Property<string>("PowerplayState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Powers")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReserveLevel")
                        .HasColumnType("int");

                    b.Property<string>("StarClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("StarPosX")
                        .HasColumnType("float");

                    b.Property<double?>("StarPosY")
                        .HasColumnType("float");

                    b.Property<double?>("StarPosZ")
                        .HasColumnType("float");

                    b.Property<string>("StarSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("SystemAddress")
                        .HasColumnType("bigint");

                    b.Property<string>("SystemAllegiance")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SystemEconomy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SystemGovernment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SystemSecurity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StarSystem")
                        .HasDatabaseName("IX_FSDJump_StarSystem");

                    b.HasIndex("SystemAddress")
                        .HasDatabaseName("IX_FSDJump_SystemAddress");

                    b.ToTable("FSDJump");
                });

            modelBuilder.Entity("Data.Models.FSSAllBodiesFound", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bodies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BodyCount")
                        .HasColumnType("int");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ScanTime")
                        .HasColumnType("float");

                    b.Property<string>("StarSystem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("SystemAddress")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StarSystem")
                        .HasDatabaseName("IX_FSSAllBodiesFound_StarSystem");

                    b.HasIndex("SystemAddress")
                        .HasDatabaseName("IX_FSSAllBodiesFound_SystemAddress");

                    b.ToTable("FSSAllBodiesFound");
                });
#pragma warning restore 612, 618
        }
    }
}
